CREATE TABLE api_keys (
  id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  name          VARCHAR(120) NOT NULL,
  -- Shown in the UI so a key can be identified, e.g. 'upw_a1B2c3D4'.
  key_prefix    VARCHAR(12)  NOT NULL,
  -- SHA-256 of the full key. The raw key is returned once at creation and
  -- never stored or shown again.
  key_hash      CHAR(64)     NOT NULL UNIQUE,
  status        VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
  created_by    UUID         REFERENCES admins(id) ON DELETE SET NULL,
  last_used_at  TIMESTAMPTZ,
  expires_at    TIMESTAMPTZ,
  revoked_at    TIMESTAMPTZ,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT api_keys_status_check CHECK (status IN ('ACTIVE', 'REVOKED', 'EXPIRED'))
);

CREATE INDEX api_keys_active_idx ON api_keys (status) WHERE revoked_at IS NULL;

-- An API key's capabilities are exactly these scopes. It never inherits a
-- role, and never gets SUPER_ADMIN.
CREATE TABLE api_key_scopes (
  api_key_id     UUID NOT NULL REFERENCES api_keys(id)    ON DELETE CASCADE,
  permission_id  UUID NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
  PRIMARY KEY (api_key_id, permission_id)
);

CREATE TABLE files (
  id             UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Generated by the storage provider, never derived from the uploaded
  -- filename, so a hostile filename cannot influence the path on disk.
  storage_key    VARCHAR(500) NOT NULL UNIQUE,
  original_name  VARCHAR(255) NOT NULL,
  mime_type      VARCHAR(120) NOT NULL,
  size_bytes     BIGINT       NOT NULL,
  provider       VARCHAR(20)  NOT NULL DEFAULT 'LOCAL',
  entity_type    VARCHAR(50),
  entity_id      VARCHAR(64),
  uploaded_by    UUID         REFERENCES admins(id) ON DELETE SET NULL,
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
  deleted_at     TIMESTAMPTZ,

  CONSTRAINT files_size_positive CHECK (size_bytes > 0),
  CONSTRAINT files_provider_check CHECK (provider IN ('LOCAL', 'S3', 'GCS', 'AZURE'))
);

CREATE INDEX files_entity_idx ON files (entity_type, entity_id) WHERE deleted_at IS NULL;
CREATE INDEX files_uploader_idx ON files (uploaded_by, created_at DESC);
