// ── Status enums ─────────────────────────────────────────────────────────
// Mirrored by CHECK constraints in the database. TypeScript is the first line
// of defence, the constraint is the guarantee.

export const ADMIN_STATUSES = ['ACTIVE', 'INACTIVE', 'SUSPENDED'] as const;
export type AdminStatus = (typeof ADMIN_STATUSES)[number];

export const ORGANIZATION_STATUSES = ['ACTIVE', 'INACTIVE', 'SUSPENDED'] as const;
export type OrganizationStatus = (typeof ORGANIZATION_STATUSES)[number];

export const PLAN_STATUSES = ['ACTIVE', 'INACTIVE', 'ARCHIVED'] as const;
export type PlanStatus = (typeof PLAN_STATUSES)[number];

export const BILLING_INTERVALS = ['MONTHLY', 'QUARTERLY', 'YEARLY', 'LIFETIME'] as const;
export type BillingInterval = (typeof BILLING_INTERVALS)[number];

export const SUBSCRIPTION_STATUSES = [
  'ACTIVE',
  'TRIALING',
  'PAST_DUE',
  'CANCELLED',
  'EXPIRED',
] as const;
export type SubscriptionStatus = (typeof SUBSCRIPTION_STATUSES)[number];

export const NOTIFICATION_TYPES = [
  'SYSTEM',
  'SECURITY',
  'BILLING',
  'ORGANIZATION',
  'GENERAL',
] as const;
export type NotificationType = (typeof NOTIFICATION_TYPES)[number];

export const API_KEY_STATUSES = ['ACTIVE', 'REVOKED', 'EXPIRED'] as const;
export type ApiKeyStatus = (typeof API_KEY_STATUSES)[number];

export const STORAGE_PROVIDERS = ['LOCAL', 'S3', 'GCS', 'AZURE'] as const;
export type StorageProviderName = (typeof STORAGE_PROVIDERS)[number];

/**
 * Publish state for CMS content rows - the home page sections, and anything else
 * the marketing site reads. An INACTIVE row stays editable in the admin panel
 * but is invisible to the public read endpoints; the alternative, deleting it,
 * throws away copy that is usually being rotated back in later.
 */
export const CONTENT_STATUSES = ['ACTIVE', 'INACTIVE'] as const;
export type ContentStatus = (typeof CONTENT_STATUSES)[number];

// ── Roles ────────────────────────────────────────────────────────────────

/**
 * The single seeded role.
 *
 * ADMIN is the unrestricted role: the authorization middleware short-circuits
 * every permission check for it, so it holds no role_permissions rows. Custom,
 * limited roles can still be created at runtime through POST /roles - they get
 * explicit grants and are checked normally.
 */
export const SYSTEM_ROLES = {
  ADMIN: 'ADMIN',
} as const;

export type SystemRole = (typeof SYSTEM_ROLES)[keyof typeof SYSTEM_ROLES];

/** The role that bypasses permission checks. */
export const ROOT_ROLE: SystemRole = SYSTEM_ROLES.ADMIN;

// ── Permissions ──────────────────────────────────────────────────────────
// This object is the catalogue of record. The permission seed reads from it,
// so a key here always exists in the database and a key checked in code always
// exists here.

export const PERMISSIONS = {
  ADMINS_CREATE: 'admins.create',
  ADMINS_READ: 'admins.read',
  ADMINS_UPDATE: 'admins.update',
  ADMINS_DELETE: 'admins.delete',

  ROLES_CREATE: 'roles.create',
  ROLES_READ: 'roles.read',
  ROLES_UPDATE: 'roles.update',
  ROLES_DELETE: 'roles.delete',

  PERMISSIONS_READ: 'permissions.read',

  ORGANIZATIONS_CREATE: 'organizations.create',
  ORGANIZATIONS_READ: 'organizations.read',
  ORGANIZATIONS_UPDATE: 'organizations.update',
  ORGANIZATIONS_DELETE: 'organizations.delete',

  PLANS_CREATE: 'plans.create',
  PLANS_READ: 'plans.read',
  PLANS_UPDATE: 'plans.update',
  PLANS_DELETE: 'plans.delete',

  SUBSCRIPTIONS_READ: 'subscriptions.read',
  SUBSCRIPTIONS_UPDATE: 'subscriptions.update',

  DASHBOARD_READ: 'dashboard.read',
  AUDIT_LOGS_READ: 'audit_logs.read',

  SETTINGS_READ: 'settings.read',
  SETTINGS_UPDATE: 'settings.update',

  NOTIFICATIONS_READ: 'notifications.read',
  NOTIFICATIONS_CREATE: 'notifications.create',

  API_KEYS_READ: 'api_keys.read',
  API_KEYS_CREATE: 'api_keys.create',
  API_KEYS_REVOKE: 'api_keys.revoke',

  FILES_READ: 'files.read',
  FILES_UPLOAD: 'files.upload',
  FILES_DELETE: 'files.delete',

  // Module-wide rather than per-section: a new home page section reuses these
  // four keys instead of needing its own permissions added here and seeded.
  HOME_PAGE_READ: 'home_page.read',
  HOME_PAGE_CREATE: 'home_page.create',
  HOME_PAGE_UPDATE: 'home_page.update',
  HOME_PAGE_DELETE: 'home_page.delete',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ALL_PERMISSION_KEYS = Object.values(PERMISSIONS) as PermissionKey[];

/** Human-readable descriptions, consumed by the permission seed. */
export const PERMISSION_DESCRIPTIONS: Record<PermissionKey, string> = {
  'admins.create': 'Create new administrator accounts',
  'admins.read': 'View administrator accounts',
  'admins.update': 'Update administrator accounts, status, and roles',
  'admins.delete': 'Delete administrator accounts',

  'roles.create': 'Create new roles',
  'roles.read': 'View roles and their permissions',
  'roles.update': 'Update roles and their permission grants',
  'roles.delete': 'Delete non-system roles',

  'permissions.read': 'View the permission catalogue',

  'organizations.create': 'Create customer organizations',
  'organizations.read': 'View customer organizations',
  'organizations.update': 'Update organizations and change their status',
  'organizations.delete': 'Delete customer organizations',

  'plans.create': 'Create subscription plans',
  'plans.read': 'View subscription plans',
  'plans.update': 'Update subscription plans',
  'plans.delete': 'Archive subscription plans',

  'subscriptions.read': 'View customer subscriptions',
  'subscriptions.update': 'Create, update, and cancel customer subscriptions',

  'dashboard.read': 'View platform dashboard and analytics',
  'audit_logs.read': 'View the audit trail',

  'settings.read': 'View platform settings',
  'settings.update': 'Update platform settings',

  'notifications.read': 'View notifications',
  'notifications.create': 'Create and broadcast notifications',

  'api_keys.read': 'View API keys',
  'api_keys.create': 'Create API keys',
  'api_keys.revoke': 'Revoke API keys',

  'files.read': 'View and download files',
  'files.upload': 'Upload files',
  'files.delete': 'Delete files',

  'home_page.read': 'View home page section content',
  'home_page.create': 'Create home page section content',
  'home_page.update': 'Update, reorder, and publish home page section content',
  'home_page.delete': 'Delete home page section content',
};

/**
 * Default grants for seeded system roles.
 *
 * Empty because ADMIN is the only system role, and its access is a
 * short-circuit in the authorization middleware rather than a set of rows.
 * Granting it explicitly would create a class of bug where deleting a row
 * silently downgrades the break-glass role.
 *
 * Custom roles created through POST /roles carry their own grants; this map
 * only covers roles the seed creates.
 */
export const DEFAULT_ROLE_PERMISSIONS: Partial<Record<SystemRole, PermissionKey[]>> = {};

export const ROLE_DESCRIPTIONS: Record<SystemRole, string> = {
  ADMIN: 'Unrestricted access to every platform capability',
};

// ── Audit actions ────────────────────────────────────────────────────────

export const AUDIT_ACTIONS = {
  ADMIN_LOGIN: 'ADMIN_LOGIN',
  ADMIN_LOGIN_FAILED: 'ADMIN_LOGIN_FAILED',
  ADMIN_LOGOUT: 'ADMIN_LOGOUT',
  ADMIN_LOGOUT_ALL: 'ADMIN_LOGOUT_ALL',
  ADMIN_TOKEN_REFRESHED: 'ADMIN_TOKEN_REFRESHED',
  SESSION_REUSE_DETECTED: 'SESSION_REUSE_DETECTED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED: 'PASSWORD_RESET_COMPLETED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',

  ADMIN_CREATED: 'ADMIN_CREATED',
  ADMIN_UPDATED: 'ADMIN_UPDATED',
  ADMIN_STATUS_CHANGED: 'ADMIN_STATUS_CHANGED',
  ADMIN_ROLES_CHANGED: 'ADMIN_ROLES_CHANGED',
  ADMIN_DELETED: 'ADMIN_DELETED',

  ROLE_CREATED: 'ROLE_CREATED',
  ROLE_UPDATED: 'ROLE_UPDATED',
  ROLE_PERMISSIONS_CHANGED: 'ROLE_PERMISSIONS_CHANGED',
  ROLE_DELETED: 'ROLE_DELETED',

  ORGANIZATION_CREATED: 'ORGANIZATION_CREATED',
  ORGANIZATION_UPDATED: 'ORGANIZATION_UPDATED',
  ORGANIZATION_STATUS_CHANGED: 'ORGANIZATION_STATUS_CHANGED',
  ORGANIZATION_DELETED: 'ORGANIZATION_DELETED',

  PLAN_CREATED: 'PLAN_CREATED',
  PLAN_UPDATED: 'PLAN_UPDATED',
  PLAN_ARCHIVED: 'PLAN_ARCHIVED',

  SUBSCRIPTION_CREATED: 'SUBSCRIPTION_CREATED',
  SUBSCRIPTION_UPDATED: 'SUBSCRIPTION_UPDATED',
  SUBSCRIPTION_CANCELLED: 'SUBSCRIPTION_CANCELLED',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',

  SETTINGS_UPDATED: 'SETTINGS_UPDATED',
  API_KEY_CREATED: 'API_KEY_CREATED',
  API_KEY_REVOKED: 'API_KEY_REVOKED',
  FILE_UPLOADED: 'FILE_UPLOADED',
  FILE_DELETED: 'FILE_DELETED',
  NOTIFICATION_CREATED: 'NOTIFICATION_CREATED',

  HOME_HERO_SLIDE_CREATED: 'HOME_HERO_SLIDE_CREATED',
  HOME_HERO_SLIDE_UPDATED: 'HOME_HERO_SLIDE_UPDATED',
  HOME_HERO_SLIDE_STATUS_CHANGED: 'HOME_HERO_SLIDE_STATUS_CHANGED',
  HOME_HERO_SLIDES_REORDERED: 'HOME_HERO_SLIDES_REORDERED',
  HOME_HERO_SLIDE_DELETED: 'HOME_HERO_SLIDE_DELETED',

  HOME_TRUST_ENTRY_CREATED: 'HOME_TRUST_ENTRY_CREATED',
  HOME_TRUST_ENTRY_UPDATED: 'HOME_TRUST_ENTRY_UPDATED',
  HOME_TRUST_ENTRY_DELETED: 'HOME_TRUST_ENTRY_DELETED',
  HOME_TRUST_ENTRIES_REORDERED: 'HOME_TRUST_ENTRIES_REORDERED',

  HOME_INDUSTRIES_ENTRY_CREATED: 'HOME_INDUSTRIES_ENTRY_CREATED',
  HOME_INDUSTRIES_ENTRY_UPDATED: 'HOME_INDUSTRIES_ENTRY_UPDATED',
  HOME_INDUSTRIES_ENTRY_DELETED: 'HOME_INDUSTRIES_ENTRY_DELETED',
  HOME_INDUSTRIES_ENTRIES_REORDERED: 'HOME_INDUSTRIES_ENTRIES_REORDERED',

  HOME_VALUES_ENTRY_CREATED: 'HOME_VALUES_ENTRY_CREATED',
  HOME_VALUES_ENTRY_UPDATED: 'HOME_VALUES_ENTRY_UPDATED',
  HOME_VALUES_ENTRY_DELETED: 'HOME_VALUES_ENTRY_DELETED',
  HOME_VALUES_ENTRIES_REORDERED: 'HOME_VALUES_ENTRIES_REORDERED',

  HOME_INTEGRATIONS_ENTRY_CREATED: 'HOME_INTEGRATIONS_ENTRY_CREATED',
  HOME_INTEGRATIONS_ENTRY_UPDATED: 'HOME_INTEGRATIONS_ENTRY_UPDATED',
  HOME_INTEGRATIONS_ENTRY_DELETED: 'HOME_INTEGRATIONS_ENTRY_DELETED',
  HOME_INTEGRATIONS_ENTRIES_REORDERED: 'HOME_INTEGRATIONS_ENTRIES_REORDERED',

  HOME_TESTIMONIAL_ENTRY_CREATED: 'HOME_TESTIMONIAL_ENTRY_CREATED',
  HOME_TESTIMONIAL_ENTRY_UPDATED: 'HOME_TESTIMONIAL_ENTRY_UPDATED',
  HOME_TESTIMONIAL_ENTRY_DELETED: 'HOME_TESTIMONIAL_ENTRY_DELETED',
  HOME_TESTIMONIAL_ENTRIES_REORDERED: 'HOME_TESTIMONIAL_ENTRIES_REORDERED',

  HOME_FAQ_ENTRY_CREATED: 'HOME_FAQ_ENTRY_CREATED',
  HOME_FAQ_ENTRY_UPDATED: 'HOME_FAQ_ENTRY_UPDATED',
  HOME_FAQ_ENTRY_DELETED: 'HOME_FAQ_ENTRY_DELETED',
  HOME_FAQ_ENTRIES_REORDERED: 'HOME_FAQ_ENTRIES_REORDERED',

  HOME_SECTION_COPY_UPDATED: 'HOME_SECTION_COPY_UPDATED',
  HOME_CTA_SECTION_UPDATED: 'HOME_CTA_SECTION_UPDATED',

  ERP_HERO_SLIDE_CREATED: 'ERP_HERO_SLIDE_CREATED',
  ERP_HERO_SLIDE_UPDATED: 'ERP_HERO_SLIDE_UPDATED',
  ERP_HERO_SLIDE_DELETED: 'ERP_HERO_SLIDE_DELETED',
  ERP_HERO_SLIDES_REORDERED: 'ERP_HERO_SLIDES_REORDERED',

  ERP_FAQ_ENTRY_CREATED: 'ERP_FAQ_ENTRY_CREATED',
  ERP_FAQ_ENTRY_UPDATED: 'ERP_FAQ_ENTRY_UPDATED',
  ERP_FAQ_ENTRY_DELETED: 'ERP_FAQ_ENTRY_DELETED',
  ERP_FAQ_ENTRIES_REORDERED: 'ERP_FAQ_ENTRIES_REORDERED',

  ERP_CTA_SECTION_UPDATED: 'ERP_CTA_SECTION_UPDATED',

  ERP_TRUST_ENTRY_CREATED: 'ERP_TRUST_ENTRY_CREATED',
  ERP_TRUST_ENTRY_UPDATED: 'ERP_TRUST_ENTRY_UPDATED',
  ERP_TRUST_ENTRY_DELETED: 'ERP_TRUST_ENTRY_DELETED',
  ERP_TRUST_ENTRIES_REORDERED: 'ERP_TRUST_ENTRIES_REORDERED',

  ERP_INDUSTRY_CREATED: 'ERP_INDUSTRY_CREATED',
  ERP_INDUSTRY_UPDATED: 'ERP_INDUSTRY_UPDATED',
  ERP_INDUSTRY_DELETED: 'ERP_INDUSTRY_DELETED',
  ERP_INDUSTRIES_REORDERED: 'ERP_INDUSTRIES_REORDERED',

  ERP_INDUSTRY_FEATURE_CREATED: 'ERP_INDUSTRY_FEATURE_CREATED',
  ERP_INDUSTRY_FEATURE_UPDATED: 'ERP_INDUSTRY_FEATURE_UPDATED',
  ERP_INDUSTRY_FEATURE_DELETED: 'ERP_INDUSTRY_FEATURE_DELETED',
  ERP_INDUSTRY_FEATURES_REORDERED: 'ERP_INDUSTRY_FEATURES_REORDERED',

  ERP_INDUSTRY_BENEFIT_CREATED: 'ERP_INDUSTRY_BENEFIT_CREATED',
  ERP_INDUSTRY_BENEFIT_UPDATED: 'ERP_INDUSTRY_BENEFIT_UPDATED',
  ERP_INDUSTRY_BENEFIT_DELETED: 'ERP_INDUSTRY_BENEFIT_DELETED',
  ERP_INDUSTRY_BENEFITS_REORDERED: 'ERP_INDUSTRY_BENEFITS_REORDERED',

  ERP_JOURNEY_PERSONA_CREATED: 'ERP_JOURNEY_PERSONA_CREATED',
  ERP_JOURNEY_PERSONA_UPDATED: 'ERP_JOURNEY_PERSONA_UPDATED',
  ERP_JOURNEY_PERSONA_DELETED: 'ERP_JOURNEY_PERSONA_DELETED',
  ERP_JOURNEY_PERSONAS_REORDERED: 'ERP_JOURNEY_PERSONAS_REORDERED',

  ERP_JOURNEY_OUTCOME_CREATED: 'ERP_JOURNEY_OUTCOME_CREATED',
  ERP_JOURNEY_OUTCOME_UPDATED: 'ERP_JOURNEY_OUTCOME_UPDATED',
  ERP_JOURNEY_OUTCOME_DELETED: 'ERP_JOURNEY_OUTCOME_DELETED',
  ERP_JOURNEY_OUTCOMES_REORDERED: 'ERP_JOURNEY_OUTCOMES_REORDERED',

  ERP_JOURNEY_POINT_CREATED: 'ERP_JOURNEY_POINT_CREATED',
  ERP_JOURNEY_POINT_UPDATED: 'ERP_JOURNEY_POINT_UPDATED',
  ERP_JOURNEY_POINT_DELETED: 'ERP_JOURNEY_POINT_DELETED',
  ERP_JOURNEY_POINTS_REORDERED: 'ERP_JOURNEY_POINTS_REORDERED',

  ERP_JOURNEY_STAT_CREATED: 'ERP_JOURNEY_STAT_CREATED',
  ERP_JOURNEY_STAT_UPDATED: 'ERP_JOURNEY_STAT_UPDATED',
  ERP_JOURNEY_STAT_DELETED: 'ERP_JOURNEY_STAT_DELETED',
  ERP_JOURNEY_STATS_REORDERED: 'ERP_JOURNEY_STATS_REORDERED',

  COMPARISON_SECTION_UPDATED: 'COMPARISON_SECTION_UPDATED',

  COMPARISON_COLUMN_CREATED: 'COMPARISON_COLUMN_CREATED',
  COMPARISON_COLUMN_UPDATED: 'COMPARISON_COLUMN_UPDATED',
  COMPARISON_COLUMN_DELETED: 'COMPARISON_COLUMN_DELETED',
  COMPARISON_COLUMNS_REORDERED: 'COMPARISON_COLUMNS_REORDERED',

  COMPARISON_CATEGORY_CREATED: 'COMPARISON_CATEGORY_CREATED',
  COMPARISON_CATEGORY_UPDATED: 'COMPARISON_CATEGORY_UPDATED',
  COMPARISON_CATEGORY_DELETED: 'COMPARISON_CATEGORY_DELETED',
  COMPARISON_CATEGORIES_REORDERED: 'COMPARISON_CATEGORIES_REORDERED',

  COMPARISON_ROW_CREATED: 'COMPARISON_ROW_CREATED',
  COMPARISON_ROW_UPDATED: 'COMPARISON_ROW_UPDATED',
  COMPARISON_ROW_DELETED: 'COMPARISON_ROW_DELETED',
  COMPARISON_ROWS_REORDERED: 'COMPARISON_ROWS_REORDERED',

  ERP_OUTCOME_CARD_CREATED: 'ERP_OUTCOME_CARD_CREATED',
  ERP_OUTCOME_CARD_UPDATED: 'ERP_OUTCOME_CARD_UPDATED',
  ERP_OUTCOME_CARD_DELETED: 'ERP_OUTCOME_CARD_DELETED',
  ERP_OUTCOME_CARDS_REORDERED: 'ERP_OUTCOME_CARDS_REORDERED',

  ERP_ESTABLISHER_BADGE_CREATED: 'ERP_ESTABLISHER_BADGE_CREATED',
  ERP_ESTABLISHER_BADGE_UPDATED: 'ERP_ESTABLISHER_BADGE_UPDATED',
  ERP_ESTABLISHER_BADGE_DELETED: 'ERP_ESTABLISHER_BADGE_DELETED',
  ERP_ESTABLISHER_BADGES_REORDERED: 'ERP_ESTABLISHER_BADGES_REORDERED',

  SFA_HERO_SLIDE_CREATED: 'SFA_HERO_SLIDE_CREATED',
  SFA_HERO_SLIDE_UPDATED: 'SFA_HERO_SLIDE_UPDATED',
  SFA_HERO_SLIDE_DELETED: 'SFA_HERO_SLIDE_DELETED',
  SFA_HERO_SLIDES_REORDERED: 'SFA_HERO_SLIDES_REORDERED',

  SFA_FAQ_ENTRY_CREATED: 'SFA_FAQ_ENTRY_CREATED',
  SFA_FAQ_ENTRY_UPDATED: 'SFA_FAQ_ENTRY_UPDATED',
  SFA_FAQ_ENTRY_DELETED: 'SFA_FAQ_ENTRY_DELETED',
  SFA_FAQ_ENTRIES_REORDERED: 'SFA_FAQ_ENTRIES_REORDERED',

  SFA_CTA_SECTION_UPDATED: 'SFA_CTA_SECTION_UPDATED',

  SFA_PROOF_PANEL_UPDATED: 'SFA_PROOF_PANEL_UPDATED',

  SFA_PROOF_LOGO_CREATED: 'SFA_PROOF_LOGO_CREATED',
  SFA_PROOF_LOGO_UPDATED: 'SFA_PROOF_LOGO_UPDATED',
  SFA_PROOF_LOGO_DELETED: 'SFA_PROOF_LOGO_DELETED',
  SFA_PROOF_LOGOS_REORDERED: 'SFA_PROOF_LOGOS_REORDERED',

  SFA_PROOF_STAT_CREATED: 'SFA_PROOF_STAT_CREATED',
  SFA_PROOF_STAT_UPDATED: 'SFA_PROOF_STAT_UPDATED',
  SFA_PROOF_STAT_DELETED: 'SFA_PROOF_STAT_DELETED',
  SFA_PROOF_STATS_REORDERED: 'SFA_PROOF_STATS_REORDERED',

  SFA_VIDEO_ENTRY_CREATED: 'SFA_VIDEO_ENTRY_CREATED',
  SFA_VIDEO_ENTRY_UPDATED: 'SFA_VIDEO_ENTRY_UPDATED',
  SFA_VIDEO_ENTRY_DELETED: 'SFA_VIDEO_ENTRY_DELETED',
  SFA_VIDEO_ENTRIES_REORDERED: 'SFA_VIDEO_ENTRIES_REORDERED',

  SFA_PACKAGE_CARD_CREATED: 'SFA_PACKAGE_CARD_CREATED',
  SFA_PACKAGE_CARD_UPDATED: 'SFA_PACKAGE_CARD_UPDATED',
  SFA_PACKAGE_CARD_DELETED: 'SFA_PACKAGE_CARD_DELETED',
  SFA_PACKAGE_CARDS_REORDERED: 'SFA_PACKAGE_CARDS_REORDERED',

  SFA_PACKAGE_FEATURE_CREATED: 'SFA_PACKAGE_FEATURE_CREATED',
  SFA_PACKAGE_FEATURE_UPDATED: 'SFA_PACKAGE_FEATURE_UPDATED',
  SFA_PACKAGE_FEATURE_DELETED: 'SFA_PACKAGE_FEATURE_DELETED',
  SFA_PACKAGE_FEATURES_REORDERED: 'SFA_PACKAGE_FEATURES_REORDERED',

  SFA_COMPLIANCE_SECTION_UPDATED: 'SFA_COMPLIANCE_SECTION_UPDATED',

  SFA_COMPLIANCE_BADGE_CREATED: 'SFA_COMPLIANCE_BADGE_CREATED',
  SFA_COMPLIANCE_BADGE_UPDATED: 'SFA_COMPLIANCE_BADGE_UPDATED',
  SFA_COMPLIANCE_BADGE_DELETED: 'SFA_COMPLIANCE_BADGE_DELETED',
  SFA_COMPLIANCE_BADGES_REORDERED: 'SFA_COMPLIANCE_BADGES_REORDERED',

  SFA_ALTERNATIVES_SECTION_UPDATED: 'SFA_ALTERNATIVES_SECTION_UPDATED',
  SFA_ALTERNATIVES_COLUMN_CREATED: 'SFA_ALTERNATIVES_COLUMN_CREATED',
  SFA_ALTERNATIVES_COLUMN_UPDATED: 'SFA_ALTERNATIVES_COLUMN_UPDATED',
  SFA_ALTERNATIVES_COLUMN_DELETED: 'SFA_ALTERNATIVES_COLUMN_DELETED',
  SFA_ALTERNATIVES_COLUMNS_REORDERED: 'SFA_ALTERNATIVES_COLUMNS_REORDERED',
  SFA_ALTERNATIVES_ROW_CREATED: 'SFA_ALTERNATIVES_ROW_CREATED',
  SFA_ALTERNATIVES_ROW_UPDATED: 'SFA_ALTERNATIVES_ROW_UPDATED',
  SFA_ALTERNATIVES_ROW_DELETED: 'SFA_ALTERNATIVES_ROW_DELETED',
  SFA_ALTERNATIVES_ROWS_REORDERED: 'SFA_ALTERNATIVES_ROWS_REORDERED',
  SFA_ALTERNATIVES_SUMMARY_UPDATED: 'SFA_ALTERNATIVES_SUMMARY_UPDATED',
  SFA_ALTERNATIVES_SUMMARY_DELETED: 'SFA_ALTERNATIVES_SUMMARY_DELETED',

  SFA_OUTCOME_SECTION_UPDATED: 'SFA_OUTCOME_SECTION_UPDATED',
  SFA_OUTCOME_CARD_CREATED: 'SFA_OUTCOME_CARD_CREATED',
  SFA_OUTCOME_CARD_UPDATED: 'SFA_OUTCOME_CARD_UPDATED',
  SFA_OUTCOME_CARD_DELETED: 'SFA_OUTCOME_CARD_DELETED',
  SFA_OUTCOME_CARDS_REORDERED: 'SFA_OUTCOME_CARDS_REORDERED',

  FMS_HERO_SLIDE_CREATED: 'FMS_HERO_SLIDE_CREATED',
  FMS_HERO_SLIDE_UPDATED: 'FMS_HERO_SLIDE_UPDATED',
  FMS_HERO_SLIDE_DELETED: 'FMS_HERO_SLIDE_DELETED',
  FMS_HERO_SLIDES_REORDERED: 'FMS_HERO_SLIDES_REORDERED',

  FMS_FAQ_ENTRY_CREATED: 'FMS_FAQ_ENTRY_CREATED',
  FMS_FAQ_ENTRY_UPDATED: 'FMS_FAQ_ENTRY_UPDATED',
  FMS_FAQ_ENTRY_DELETED: 'FMS_FAQ_ENTRY_DELETED',
  FMS_FAQ_ENTRIES_REORDERED: 'FMS_FAQ_ENTRIES_REORDERED',

  FMS_CTA_SECTION_UPDATED: 'FMS_CTA_SECTION_UPDATED',

  BAKERY_HERO_SLIDE_CREATED: 'BAKERY_HERO_SLIDE_CREATED',
  BAKERY_HERO_SLIDE_UPDATED: 'BAKERY_HERO_SLIDE_UPDATED',
  BAKERY_HERO_SLIDE_DELETED: 'BAKERY_HERO_SLIDE_DELETED',
  BAKERY_HERO_SLIDES_REORDERED: 'BAKERY_HERO_SLIDES_REORDERED',

  BAKERY_TRUST_LOGO_CREATED: 'BAKERY_TRUST_LOGO_CREATED',
  BAKERY_TRUST_LOGO_UPDATED: 'BAKERY_TRUST_LOGO_UPDATED',
  BAKERY_TRUST_LOGO_DELETED: 'BAKERY_TRUST_LOGO_DELETED',
  BAKERY_TRUST_LOGOS_REORDERED: 'BAKERY_TRUST_LOGOS_REORDERED',

  BAKERY_TRUST_STAT_CREATED: 'BAKERY_TRUST_STAT_CREATED',
  BAKERY_TRUST_STAT_UPDATED: 'BAKERY_TRUST_STAT_UPDATED',
  BAKERY_TRUST_STAT_DELETED: 'BAKERY_TRUST_STAT_DELETED',
  BAKERY_TRUST_STATS_REORDERED: 'BAKERY_TRUST_STATS_REORDERED',

  BAKERY_PLATFORM_TILE_CREATED: 'BAKERY_PLATFORM_TILE_CREATED',
  BAKERY_PLATFORM_TILE_UPDATED: 'BAKERY_PLATFORM_TILE_UPDATED',
  BAKERY_PLATFORM_TILE_DELETED: 'BAKERY_PLATFORM_TILE_DELETED',
  BAKERY_PLATFORM_TILES_REORDERED: 'BAKERY_PLATFORM_TILES_REORDERED',

  BAKERY_HELP_VISUAL_CREATED: 'BAKERY_HELP_VISUAL_CREATED',
  BAKERY_HELP_VISUAL_UPDATED: 'BAKERY_HELP_VISUAL_UPDATED',
  BAKERY_HELP_VISUAL_DELETED: 'BAKERY_HELP_VISUAL_DELETED',
  BAKERY_HELP_VISUALS_REORDERED: 'BAKERY_HELP_VISUALS_REORDERED',

  BAKERY_FAQ_ENTRY_CREATED: 'BAKERY_FAQ_ENTRY_CREATED',
  BAKERY_FAQ_ENTRY_UPDATED: 'BAKERY_FAQ_ENTRY_UPDATED',
  BAKERY_FAQ_ENTRY_DELETED: 'BAKERY_FAQ_ENTRY_DELETED',
  BAKERY_FAQ_ENTRIES_REORDERED: 'BAKERY_FAQ_ENTRIES_REORDERED',

  BAKERY_CTA_FEATURE_CREATED: 'BAKERY_CTA_FEATURE_CREATED',
  BAKERY_CTA_FEATURE_UPDATED: 'BAKERY_CTA_FEATURE_UPDATED',
  BAKERY_CTA_FEATURE_DELETED: 'BAKERY_CTA_FEATURE_DELETED',
  BAKERY_CTA_FEATURES_REORDERED: 'BAKERY_CTA_FEATURES_REORDERED',

  BAKERY_CTA_SECTION_UPDATED: 'BAKERY_CTA_SECTION_UPDATED',

  FMCG_HERO_SLIDE_CREATED: 'FMCG_HERO_SLIDE_CREATED',
  FMCG_HERO_SLIDE_UPDATED: 'FMCG_HERO_SLIDE_UPDATED',
  FMCG_HERO_SLIDE_DELETED: 'FMCG_HERO_SLIDE_DELETED',
  FMCG_HERO_SLIDES_REORDERED: 'FMCG_HERO_SLIDES_REORDERED',

  FMCG_TRUST_LOGO_CREATED: 'FMCG_TRUST_LOGO_CREATED',
  FMCG_TRUST_LOGO_UPDATED: 'FMCG_TRUST_LOGO_UPDATED',
  FMCG_TRUST_LOGO_DELETED: 'FMCG_TRUST_LOGO_DELETED',
  FMCG_TRUST_LOGOS_REORDERED: 'FMCG_TRUST_LOGOS_REORDERED',

  FMCG_TRUST_STAT_CREATED: 'FMCG_TRUST_STAT_CREATED',
  FMCG_TRUST_STAT_UPDATED: 'FMCG_TRUST_STAT_UPDATED',
  FMCG_TRUST_STAT_DELETED: 'FMCG_TRUST_STAT_DELETED',
  FMCG_TRUST_STATS_REORDERED: 'FMCG_TRUST_STATS_REORDERED',

  FMCG_PLATFORM_TILE_CREATED: 'FMCG_PLATFORM_TILE_CREATED',
  FMCG_PLATFORM_TILE_UPDATED: 'FMCG_PLATFORM_TILE_UPDATED',
  FMCG_PLATFORM_TILE_DELETED: 'FMCG_PLATFORM_TILE_DELETED',
  FMCG_PLATFORM_TILES_REORDERED: 'FMCG_PLATFORM_TILES_REORDERED',

  FMCG_FAQ_ENTRY_CREATED: 'FMCG_FAQ_ENTRY_CREATED',
  FMCG_FAQ_ENTRY_UPDATED: 'FMCG_FAQ_ENTRY_UPDATED',
  FMCG_FAQ_ENTRY_DELETED: 'FMCG_FAQ_ENTRY_DELETED',
  FMCG_FAQ_ENTRIES_REORDERED: 'FMCG_FAQ_ENTRIES_REORDERED',

  FMCG_CTA_SECTION_UPDATED: 'FMCG_CTA_SECTION_UPDATED',

  SWEETS_HERO_SLIDE_CREATED: 'SWEETS_HERO_SLIDE_CREATED',
  SWEETS_HERO_SLIDE_UPDATED: 'SWEETS_HERO_SLIDE_UPDATED',
  SWEETS_HERO_SLIDE_DELETED: 'SWEETS_HERO_SLIDE_DELETED',
  SWEETS_HERO_SLIDES_REORDERED: 'SWEETS_HERO_SLIDES_REORDERED',

  SWEETS_TRUST_LOGO_CREATED: 'SWEETS_TRUST_LOGO_CREATED',
  SWEETS_TRUST_LOGO_UPDATED: 'SWEETS_TRUST_LOGO_UPDATED',
  SWEETS_TRUST_LOGO_DELETED: 'SWEETS_TRUST_LOGO_DELETED',
  SWEETS_TRUST_LOGOS_REORDERED: 'SWEETS_TRUST_LOGOS_REORDERED',

  SWEETS_TRUST_STAT_CREATED: 'SWEETS_TRUST_STAT_CREATED',
  SWEETS_TRUST_STAT_UPDATED: 'SWEETS_TRUST_STAT_UPDATED',
  SWEETS_TRUST_STAT_DELETED: 'SWEETS_TRUST_STAT_DELETED',
  SWEETS_TRUST_STATS_REORDERED: 'SWEETS_TRUST_STATS_REORDERED',

  SWEETS_PLATFORM_TILE_CREATED: 'SWEETS_PLATFORM_TILE_CREATED',
  SWEETS_PLATFORM_TILE_UPDATED: 'SWEETS_PLATFORM_TILE_UPDATED',
  SWEETS_PLATFORM_TILE_DELETED: 'SWEETS_PLATFORM_TILE_DELETED',
  SWEETS_PLATFORM_TILES_REORDERED: 'SWEETS_PLATFORM_TILES_REORDERED',

  SWEETS_FAQ_ENTRY_CREATED: 'SWEETS_FAQ_ENTRY_CREATED',
  SWEETS_FAQ_ENTRY_UPDATED: 'SWEETS_FAQ_ENTRY_UPDATED',
  SWEETS_FAQ_ENTRY_DELETED: 'SWEETS_FAQ_ENTRY_DELETED',
  SWEETS_FAQ_ENTRIES_REORDERED: 'SWEETS_FAQ_ENTRIES_REORDERED',

  SWEETS_CTA_SECTION_UPDATED: 'SWEETS_CTA_SECTION_UPDATED',

  FOOD_PROCESSING_HERO_SLIDE_CREATED: 'FOOD_PROCESSING_HERO_SLIDE_CREATED',
  FOOD_PROCESSING_HERO_SLIDE_UPDATED: 'FOOD_PROCESSING_HERO_SLIDE_UPDATED',
  FOOD_PROCESSING_HERO_SLIDE_DELETED: 'FOOD_PROCESSING_HERO_SLIDE_DELETED',
  FOOD_PROCESSING_HERO_SLIDES_REORDERED: 'FOOD_PROCESSING_HERO_SLIDES_REORDERED',

  FOOD_PROCESSING_TRUST_LOGO_CREATED: 'FOOD_PROCESSING_TRUST_LOGO_CREATED',
  FOOD_PROCESSING_TRUST_LOGO_UPDATED: 'FOOD_PROCESSING_TRUST_LOGO_UPDATED',
  FOOD_PROCESSING_TRUST_LOGO_DELETED: 'FOOD_PROCESSING_TRUST_LOGO_DELETED',
  FOOD_PROCESSING_TRUST_LOGOS_REORDERED: 'FOOD_PROCESSING_TRUST_LOGOS_REORDERED',

  FOOD_PROCESSING_TRUST_STAT_CREATED: 'FOOD_PROCESSING_TRUST_STAT_CREATED',
  FOOD_PROCESSING_TRUST_STAT_UPDATED: 'FOOD_PROCESSING_TRUST_STAT_UPDATED',
  FOOD_PROCESSING_TRUST_STAT_DELETED: 'FOOD_PROCESSING_TRUST_STAT_DELETED',
  FOOD_PROCESSING_TRUST_STATS_REORDERED: 'FOOD_PROCESSING_TRUST_STATS_REORDERED',

  FOOD_PROCESSING_PLATFORM_TILE_CREATED: 'FOOD_PROCESSING_PLATFORM_TILE_CREATED',
  FOOD_PROCESSING_PLATFORM_TILE_UPDATED: 'FOOD_PROCESSING_PLATFORM_TILE_UPDATED',
  FOOD_PROCESSING_PLATFORM_TILE_DELETED: 'FOOD_PROCESSING_PLATFORM_TILE_DELETED',
  FOOD_PROCESSING_PLATFORM_TILES_REORDERED: 'FOOD_PROCESSING_PLATFORM_TILES_REORDERED',

  FOOD_PROCESSING_FAQ_ENTRY_CREATED: 'FOOD_PROCESSING_FAQ_ENTRY_CREATED',
  FOOD_PROCESSING_FAQ_ENTRY_UPDATED: 'FOOD_PROCESSING_FAQ_ENTRY_UPDATED',
  FOOD_PROCESSING_FAQ_ENTRY_DELETED: 'FOOD_PROCESSING_FAQ_ENTRY_DELETED',
  FOOD_PROCESSING_FAQ_ENTRIES_REORDERED: 'FOOD_PROCESSING_FAQ_ENTRIES_REORDERED',

  FOOD_PROCESSING_COVERAGE_ITEM_CREATED: 'FOOD_PROCESSING_COVERAGE_ITEM_CREATED',
  FOOD_PROCESSING_COVERAGE_ITEM_UPDATED: 'FOOD_PROCESSING_COVERAGE_ITEM_UPDATED',
  FOOD_PROCESSING_COVERAGE_ITEM_DELETED: 'FOOD_PROCESSING_COVERAGE_ITEM_DELETED',
  FOOD_PROCESSING_COVERAGE_ITEMS_REORDERED: 'FOOD_PROCESSING_COVERAGE_ITEMS_REORDERED',

  FOOD_PROCESSING_CTA_SECTION_UPDATED: 'FOOD_PROCESSING_CTA_SECTION_UPDATED',
  FOOD_PROCESSING_TRUST_PANEL_UPDATED: 'FOOD_PROCESSING_TRUST_PANEL_UPDATED',

  NON_FOOD_FMCG_HERO_SLIDE_CREATED: 'NON_FOOD_FMCG_HERO_SLIDE_CREATED',
  NON_FOOD_FMCG_HERO_SLIDE_UPDATED: 'NON_FOOD_FMCG_HERO_SLIDE_UPDATED',
  NON_FOOD_FMCG_HERO_SLIDE_DELETED: 'NON_FOOD_FMCG_HERO_SLIDE_DELETED',
  NON_FOOD_FMCG_HERO_SLIDES_REORDERED: 'NON_FOOD_FMCG_HERO_SLIDES_REORDERED',

  NON_FOOD_FMCG_TRUST_LOGO_CREATED: 'NON_FOOD_FMCG_TRUST_LOGO_CREATED',
  NON_FOOD_FMCG_TRUST_LOGO_UPDATED: 'NON_FOOD_FMCG_TRUST_LOGO_UPDATED',
  NON_FOOD_FMCG_TRUST_LOGO_DELETED: 'NON_FOOD_FMCG_TRUST_LOGO_DELETED',
  NON_FOOD_FMCG_TRUST_LOGOS_REORDERED: 'NON_FOOD_FMCG_TRUST_LOGOS_REORDERED',

  NON_FOOD_FMCG_TRUST_STAT_CREATED: 'NON_FOOD_FMCG_TRUST_STAT_CREATED',
  NON_FOOD_FMCG_TRUST_STAT_UPDATED: 'NON_FOOD_FMCG_TRUST_STAT_UPDATED',
  NON_FOOD_FMCG_TRUST_STAT_DELETED: 'NON_FOOD_FMCG_TRUST_STAT_DELETED',
  NON_FOOD_FMCG_TRUST_STATS_REORDERED: 'NON_FOOD_FMCG_TRUST_STATS_REORDERED',

  NON_FOOD_FMCG_PLATFORM_TILE_CREATED: 'NON_FOOD_FMCG_PLATFORM_TILE_CREATED',
  NON_FOOD_FMCG_PLATFORM_TILE_UPDATED: 'NON_FOOD_FMCG_PLATFORM_TILE_UPDATED',
  NON_FOOD_FMCG_PLATFORM_TILE_DELETED: 'NON_FOOD_FMCG_PLATFORM_TILE_DELETED',
  NON_FOOD_FMCG_PLATFORM_TILES_REORDERED: 'NON_FOOD_FMCG_PLATFORM_TILES_REORDERED',

  NON_FOOD_FMCG_FAQ_ENTRY_CREATED: 'NON_FOOD_FMCG_FAQ_ENTRY_CREATED',
  NON_FOOD_FMCG_FAQ_ENTRY_UPDATED: 'NON_FOOD_FMCG_FAQ_ENTRY_UPDATED',
  NON_FOOD_FMCG_FAQ_ENTRY_DELETED: 'NON_FOOD_FMCG_FAQ_ENTRY_DELETED',
  NON_FOOD_FMCG_FAQ_ENTRIES_REORDERED: 'NON_FOOD_FMCG_FAQ_ENTRIES_REORDERED',

  NON_FOOD_FMCG_CAPABILITY_CARD_CREATED: 'NON_FOOD_FMCG_CAPABILITY_CARD_CREATED',
  NON_FOOD_FMCG_CAPABILITY_CARD_UPDATED: 'NON_FOOD_FMCG_CAPABILITY_CARD_UPDATED',
  NON_FOOD_FMCG_CAPABILITY_CARD_DELETED: 'NON_FOOD_FMCG_CAPABILITY_CARD_DELETED',
  NON_FOOD_FMCG_CAPABILITY_CARDS_REORDERED: 'NON_FOOD_FMCG_CAPABILITY_CARDS_REORDERED',

  NON_FOOD_FMCG_BENEFIT_ITEM_CREATED: 'NON_FOOD_FMCG_BENEFIT_ITEM_CREATED',
  NON_FOOD_FMCG_BENEFIT_ITEM_UPDATED: 'NON_FOOD_FMCG_BENEFIT_ITEM_UPDATED',
  NON_FOOD_FMCG_BENEFIT_ITEM_DELETED: 'NON_FOOD_FMCG_BENEFIT_ITEM_DELETED',
  NON_FOOD_FMCG_BENEFIT_ITEMS_REORDERED: 'NON_FOOD_FMCG_BENEFIT_ITEMS_REORDERED',

  NON_FOOD_FMCG_COVERAGE_ITEM_CREATED: 'NON_FOOD_FMCG_COVERAGE_ITEM_CREATED',
  NON_FOOD_FMCG_COVERAGE_ITEM_UPDATED: 'NON_FOOD_FMCG_COVERAGE_ITEM_UPDATED',
  NON_FOOD_FMCG_COVERAGE_ITEM_DELETED: 'NON_FOOD_FMCG_COVERAGE_ITEM_DELETED',
  NON_FOOD_FMCG_COVERAGE_ITEMS_REORDERED: 'NON_FOOD_FMCG_COVERAGE_ITEMS_REORDERED',

  NON_FOOD_FMCG_CTA_SECTION_UPDATED: 'NON_FOOD_FMCG_CTA_SECTION_UPDATED',
  NON_FOOD_FMCG_COVERAGE_PANEL_UPDATED: 'NON_FOOD_FMCG_COVERAGE_PANEL_UPDATED',

  DAIRY_HERO_SLIDE_CREATED: 'DAIRY_HERO_SLIDE_CREATED',
  DAIRY_HERO_SLIDE_UPDATED: 'DAIRY_HERO_SLIDE_UPDATED',
  DAIRY_HERO_SLIDE_DELETED: 'DAIRY_HERO_SLIDE_DELETED',
  DAIRY_HERO_SLIDES_REORDERED: 'DAIRY_HERO_SLIDES_REORDERED',

  DAIRY_TRUST_LOGO_CREATED: 'DAIRY_TRUST_LOGO_CREATED',
  DAIRY_TRUST_LOGO_UPDATED: 'DAIRY_TRUST_LOGO_UPDATED',
  DAIRY_TRUST_LOGO_DELETED: 'DAIRY_TRUST_LOGO_DELETED',
  DAIRY_TRUST_LOGOS_REORDERED: 'DAIRY_TRUST_LOGOS_REORDERED',

  DAIRY_TRUST_STAT_CREATED: 'DAIRY_TRUST_STAT_CREATED',
  DAIRY_TRUST_STAT_UPDATED: 'DAIRY_TRUST_STAT_UPDATED',
  DAIRY_TRUST_STAT_DELETED: 'DAIRY_TRUST_STAT_DELETED',
  DAIRY_TRUST_STATS_REORDERED: 'DAIRY_TRUST_STATS_REORDERED',

  DAIRY_CAPABILITY_CARD_CREATED: 'DAIRY_CAPABILITY_CARD_CREATED',
  DAIRY_CAPABILITY_CARD_UPDATED: 'DAIRY_CAPABILITY_CARD_UPDATED',
  DAIRY_CAPABILITY_CARD_DELETED: 'DAIRY_CAPABILITY_CARD_DELETED',
  DAIRY_CAPABILITY_CARDS_REORDERED: 'DAIRY_CAPABILITY_CARDS_REORDERED',

  DAIRY_PLATFORM_TILE_CREATED: 'DAIRY_PLATFORM_TILE_CREATED',
  DAIRY_PLATFORM_TILE_UPDATED: 'DAIRY_PLATFORM_TILE_UPDATED',
  DAIRY_PLATFORM_TILE_DELETED: 'DAIRY_PLATFORM_TILE_DELETED',
  DAIRY_PLATFORM_TILES_REORDERED: 'DAIRY_PLATFORM_TILES_REORDERED',

  DAIRY_BENEFIT_ITEM_CREATED: 'DAIRY_BENEFIT_ITEM_CREATED',
  DAIRY_BENEFIT_ITEM_UPDATED: 'DAIRY_BENEFIT_ITEM_UPDATED',
  DAIRY_BENEFIT_ITEM_DELETED: 'DAIRY_BENEFIT_ITEM_DELETED',
  DAIRY_BENEFIT_ITEMS_REORDERED: 'DAIRY_BENEFIT_ITEMS_REORDERED',

  DAIRY_COVERAGE_ITEM_CREATED: 'DAIRY_COVERAGE_ITEM_CREATED',
  DAIRY_COVERAGE_ITEM_UPDATED: 'DAIRY_COVERAGE_ITEM_UPDATED',
  DAIRY_COVERAGE_ITEM_DELETED: 'DAIRY_COVERAGE_ITEM_DELETED',
  DAIRY_COVERAGE_ITEMS_REORDERED: 'DAIRY_COVERAGE_ITEMS_REORDERED',

  DAIRY_FAQ_ENTRY_CREATED: 'DAIRY_FAQ_ENTRY_CREATED',
  DAIRY_FAQ_ENTRY_UPDATED: 'DAIRY_FAQ_ENTRY_UPDATED',
  DAIRY_FAQ_ENTRY_DELETED: 'DAIRY_FAQ_ENTRY_DELETED',
  DAIRY_FAQ_ENTRIES_REORDERED: 'DAIRY_FAQ_ENTRIES_REORDERED',

  DAIRY_CTA_SECTION_UPDATED: 'DAIRY_CTA_SECTION_UPDATED',
  DAIRY_CAPABILITIES_PANEL_UPDATED: 'DAIRY_CAPABILITIES_PANEL_UPDATED',
  DAIRY_BENEFITS_PANEL_UPDATED: 'DAIRY_BENEFITS_PANEL_UPDATED',

  UNAUTHORIZED_ACCESS_ATTEMPT: 'UNAUTHORIZED_ACCESS_ATTEMPT',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

// ── Settings ─────────────────────────────────────────────────────────────

export const SETTING_KEYS = {
  PLATFORM_NAME: 'platform_name',
  SUPPORT_EMAIL: 'support_email',
  MAINTENANCE_MODE: 'maintenance_mode',
  DEFAULT_SUBSCRIPTION_PLAN: 'default_subscription_plan',
  SECURITY_SETTINGS: 'security_settings',
} as const;

// ── Misc limits ──────────────────────────────────────────────────────────

export const LIMITS = {
  MAX_ROLES_PER_ADMIN: 20,
  MAX_PERMISSIONS_PER_ROLE: 200,
  SESSION_RETENTION_DAYS: 30,
  RECENT_ACTIVITY_LIMIT: 15,
  SUBSCRIPTION_EXPIRY_HORIZON_DAYS: 30,
  ANALYTICS_MAX_DAYS: 365,
  ANALYTICS_DEFAULT_DAYS: 30,
  // The hero is an auto-rotating carousel - past a dozen slides the later ones
  // are never seen by a real visitor.
  MAX_HERO_SLIDES: 12,
  // One entry contributes at most one logo and one counter, so this caps both
  // lists at once: the marquee loops its set three times and past ~24 a visitor
  // never sees the end of a cycle, which is the tighter of the two limits.
  MAX_TRUST_ENTRIES: 24,
  // The section renders one block at a time, so this caps how many alternates
  // can sit beside the live one rather than how many are shown.
  MAX_INDUSTRIES_ENTRIES: 12,
  // A 3-up grid; past two dozen the section stops reading as a summary of how
  // the company works and starts reading as a directory.
  MAX_VALUES_ENTRIES: 24,
  // Every entry is one logo pinned to the rotating sphere. Past about two
  // dozen the badges overlap at any size the section is actually rendered at,
  // and the farthest-point sampling that spreads them has nowhere left to go.
  MAX_INTEGRATIONS_ENTRIES: 24,
  // The marquee loops its set twice and scrolls for 70 seconds. Past about
  // two dozen a visitor never reaches the end of a cycle, which is the same
  // ceiling the trust marquee runs into.
  MAX_TESTIMONIAL_ENTRIES: 24,
  // An accordion a visitor is expected to scan before buying. Past about two
  // dozen it stops being a list of objections and becomes a manual, which is
  // what the dedicated FAQ page is for.
  MAX_FAQ_ENTRIES: 24,
  // The ERP slider auto-advances every five seconds; past a dozen slides the
  // later ones are never seen by a real visitor, same as the home hero.
  MAX_ERP_HERO_SLIDES: 12,
  MAX_ERP_FAQ_ENTRIES: 24,
  // One entry contributes at most one logo and one counter, so this caps both
  // lists at once - the same ceiling the home page's marquee runs into.
  MAX_ERP_TRUST_ENTRIES: 24,
  // The counter row is a four-up grid. A fifth would wrap onto its own line
  // under three, which reads as a mistake rather than as more proof.
  MAX_ERP_TRUST_STATS: 4,
  // The selector is a single scrolling column beside the panel. Past a dozen
  // it stops being a chooser and starts being a list to read.
  MAX_ERP_INDUSTRIES: 12,
  // The panel lays features out two-up; the shipped set is six.
  MAX_ERP_INDUSTRY_FEATURES: 12,
  // The strip is a four-up grid on desktop, two-up on mobile.
  MAX_ERP_INDUSTRY_BENEFITS: 8,

  /** The left-hand audience list. Five today; past a dozen it stops scanning. */
  MAX_ERP_JOURNEY_PERSONAS: 12,

  /** Per persona, for each of the two lists in its proof panel. */
  MAX_ERP_JOURNEY_OUTCOMES: 10,
  MAX_ERP_JOURNEY_POINTS: 10,

  /**
   * The company-wide figures. Three today, and the row is a four-up grid whose
   * first cell is the persona's own headline metric - so three is what fits.
   */
  MAX_ERP_JOURNEY_STATS: 3,

  /**
   * The comparison grid.
   *
   * Columns are capped low because every one of them narrows the rest: the
   * leader column is 1.5fr and the others share what is left, so past six the
   * cells stop being readable on a laptop.
   */
  MAX_COMPARISON_COLUMNS: 6,
  MAX_COMPARISON_CATEGORIES: 12,
  MAX_COMPARISON_ROWS: 12,

  /**
   * The outcomes carousel. It scrolls, so the cap is about how much proof a
   * visitor will read rather than about what fits on screen.
   */
  MAX_ERP_OUTCOME_CARDS: 12,

  /**
   * The compliance badges beside the sphere.
   *
   * Four, because the panel is a two-by-two grid that has to stay the same
   * height as the sphere next to it - a fifth would push the two columns out
   * of step.
   */
  MAX_ERP_ESTABLISHER_BADGES: 4,

  /** The SFA-DMS page, on the same caps as the ERP page's equivalents. */
  MAX_SFA_HERO_SLIDES: 12,
  MAX_SFA_FAQ_ENTRIES: 24,

  /*
   * The proof section. The marquee scrolls, so it takes as many logos as there
   * are customers to show; the numbers beside it do not - that panel is a
   * two-by-two grid, and a fifth figure would have nowhere to go.
   */
  MAX_SFA_PROOF_LOGOS: 24,
  MAX_SFA_PROOF_STATS: 4,

  /*
   * The video section. One entry is live at a time; the rest are drafts and
   * retired clips kept for reference, which is what the cap is really about.
   */
  MAX_SFA_VIDEO_ENTRIES: 10,

  /*
   * The adoption path. The grid is three across, so three and six are the
   * counts that fill their rows; the cap allows two full rows.
   */
  MAX_SFA_PACKAGE_CARDS: 6,
  MAX_SFA_PACKAGE_FEATURES: 20,

  /*
   * The compliance panel. The badges run down a single column beside the
   * sphere, so the cap is about how tall that column can get before it
   * outruns the panel next to it rather than about a grid.
   */
  MAX_SFA_COMPLIANCE_BADGES: 6,

  /*
   * The outcome stories. A carousel, so the cap is about how far a visitor
   * will reasonably page rather than about what fits on screen.
   */
  MAX_SFA_OUTCOME_CARDS: 12,

  /** The FMS page, on the same caps as the SFA-DMS page's equivalents. */
  MAX_FMS_HERO_SLIDES: 12,
  MAX_FMS_FAQ_ENTRIES: 24,

  /** The Bakery & Confectionery industry page. */
  MAX_BAKERY_HERO_SLIDES: 12,
  // The logo row is a six-up grid; two full rows is as far as it should go.
  MAX_BAKERY_TRUST_LOGOS: 12,
  // The figures strip is a five-up grid on desktop - a sixth wraps under five.
  MAX_BAKERY_TRUST_STATS: 5,
  // Three tiles on the first row and two under them; two such rows at most.
  MAX_BAKERY_PLATFORM_TILES: 10,
  // One diagram is live; the rest are replacements being prepared.
  MAX_BAKERY_HELP_VISUALS: 10,
  MAX_BAKERY_FAQ_ENTRIES: 24,
  // The marks under the buttons are a four-up grid; a fifth wraps.
  MAX_BAKERY_CTA_FEATURES: 4,

  /** The FMCG Distribution industry page. */
  MAX_FMCG_HERO_SLIDES: 12,
  // The logos scroll as a marquee, so the cap is how many a visitor will watch
  // go by rather than what fits - the same ceiling as the home page's strip.
  MAX_FMCG_TRUST_LOGOS: 24,
  // The figures are a three-up grid; two full rows at most.
  MAX_FMCG_TRUST_STATS: 6,
  MAX_FMCG_PLATFORM_TILES: 10,
  MAX_FMCG_FAQ_ENTRIES: 24,

  /** The Sweets & Namkeen industry page. */
  MAX_SWEETS_HERO_SLIDES: 12,
  // A scrolling marquee, on the same ceiling as the FMCG page's.
  MAX_SWEETS_TRUST_LOGOS: 24,
  // The figures are a six-up row on desktop; a seventh wraps under six.
  MAX_SWEETS_TRUST_STATS: 6,
  MAX_SWEETS_PLATFORM_TILES: 10,
  MAX_SWEETS_FAQ_ENTRIES: 24,

  /** The Food Processing industry page. */
  MAX_FOOD_PROCESSING_HERO_SLIDES: 12,
  MAX_FOOD_PROCESSING_TRUST_LOGOS: 24,
  // The figures sit three-up beside the photograph; a fourth would wrap.
  MAX_FOOD_PROCESSING_TRUST_STATS: 3,
  MAX_FOOD_PROCESSING_PLATFORM_TILES: 10,
  // A wrapping six-up grid; two dozen is four full rows.
  MAX_FOOD_PROCESSING_COVERAGE_ITEMS: 24,
  MAX_FOOD_PROCESSING_FAQ_ENTRIES: 24,

  /** The Non-Food FMCG industry page. */
  MAX_NON_FOOD_FMCG_HERO_SLIDES: 12,
  MAX_NON_FOOD_FMCG_TRUST_LOGOS: 24,
  // A six-up row on desktop; a seventh wraps.
  MAX_NON_FOOD_FMCG_TRUST_STATS: 6,
  // Four-up then centred; three rows at most.
  MAX_NON_FOOD_FMCG_CAPABILITY_CARDS: 12,
  MAX_NON_FOOD_FMCG_PLATFORM_TILES: 10,
  // Three-up beside the copy; past a dozen it outruns the artwork.
  MAX_NON_FOOD_FMCG_BENEFIT_ITEMS: 12,
  // A four-up grid; two dozen is six full rows.
  MAX_NON_FOOD_FMCG_COVERAGE_ITEMS: 24,
  MAX_NON_FOOD_FMCG_FAQ_ENTRIES: 24,

  /** The Dairy & Ice Cream industry page. */
  MAX_DAIRY_HERO_SLIDES: 12,
  MAX_DAIRY_TRUST_LOGOS: 24,
  // The card rotates through the figures one at a time, each with its photo.
  MAX_DAIRY_TRUST_STATS: 6,
  // Numbered two-up beside the collage; past a dozen it outruns the artwork.
  MAX_DAIRY_CAPABILITY_CARDS: 12,
  MAX_DAIRY_PLATFORM_TILES: 10,
  // Numbered two-up beside the image; past a dozen it outruns the artwork.
  MAX_DAIRY_BENEFIT_ITEMS: 12,
  // One horizontally scrolling row; two dozen is already a long scroll.
  MAX_DAIRY_COVERAGE_ITEMS: 24,
  MAX_DAIRY_FAQ_ENTRIES: 24,
} as const;

// ── Publicly served uploads ──────────────────────────────────────────────

/**
 * The entity types whose uploaded images are served to anonymous visitors.
 *
 * Uploads are private by default: the files module requires FILES_READ and
 * hands everything back as an attachment. But an image authored for the
 * marketing home page has to load in an <img> on a site that holds no
 * credentials, so those files opt in - at upload time, by entity type.
 *
 * This is an allowlist rather than "any image by id". An unguessable UUID is
 * not authorisation, and the files table also holds uploads that were never
 * meant to leave the panel.
 */
export const PUBLIC_FILE_ENTITY_TYPES = [
  'home_hero_slide',
  'home_trust_logo',
  'home_industries_video',
  'home_values_card',
  'home_integrations_logo',
  'home_integrations_centre_logo',
  'home_testimonial_poster',
  'home_testimonial_video',
  'home_cta_image',
  'home_cta_report',
  'erp_hero_slide',
  'erp_cta_image',
  'erp_trust_logo',
  'erp_industry_image',
  'erp_industry_dashboard',
  'erp_journey_avatar',
  'sfa_hero_slide',
  'sfa_cta_image',
  'sfa_cta_dashboard',
  'sfa_proof_logo',
  'sfa_compliance_background',
  'sfa_outcome_photo',
  'fms_hero_slide',
  'fms_cta_image',
  'bakery_hero_slide',
  'bakery_trust_logo',
  'bakery_trust_stat_icon',
  'bakery_platform_icon',
  'bakery_help_visual',
  'bakery_cta_image',
  'fmcg_hero_slide',
  'fmcg_trust_logo',
  'fmcg_platform_icon',
  'fmcg_cta_image',
  'sweets_hero_slide',
  'sweets_trust_logo',
  'sweets_platform_icon',
  'sweets_cta_image',
  'food_processing_hero_slide',
  'food_processing_trust_logo',
  'food_processing_trust_panel',
  'food_processing_platform_icon',
  'food_processing_coverage_image',
  'food_processing_cta_image',
  'non_food_fmcg_hero_slide',
  'non_food_fmcg_trust_logo',
  'non_food_fmcg_capability_image',
  'non_food_fmcg_platform_icon',
  'non_food_fmcg_coverage_panel',
  'non_food_fmcg_cta_image',
  'dairy_hero_slide',
  'dairy_trust_logo',
  'dairy_trust_stat_image',
  'dairy_capabilities_panel',
  'dairy_platform_icon',
  'dairy_benefits_panel',
  'dairy_coverage_image',
  'dairy_cta_image',
  'sfa_video',
  'comparison_column_logo',
  'erp_outcome_image',
] as const;

export type PublicFileEntityType = (typeof PUBLIC_FILE_ENTITY_TYPES)[number];

/**
 * The media types the public route will serve to anonymous visitors.
 *
 * Prefixes rather than exact types, so adding a codec to the upload allowlist
 * does not also mean remembering to add it here. Everything else an admin can
 * upload - spreadsheets, CSVs, documents - stays behind authentication even
 * when it carries a public entity type.
 *
 * PDF is the one exact type on the list rather than a prefix: the home page's
 * report download hands a visitor a PDF, and no other application/* type
 * should come with it.
 */
export const PUBLIC_FILE_MIME_PREFIXES = ['image/', 'video/', 'application/pdf'] as const;

export const isPubliclyServableMimeType = (mimeType: string): boolean =>
  PUBLIC_FILE_MIME_PREFIXES.some((prefix) => mimeType.startsWith(prefix));

export const isPubliclyServableEntityType = (
  entityType: string | null,
): entityType is PublicFileEntityType =>
  entityType !== null &&
  (PUBLIC_FILE_ENTITY_TYPES as readonly string[]).includes(entityType);

// ── Page section copy ────────────────────────────────────────────────────

/**
 * The pages the CMS authors, and the sections each one shares copy across.
 *
 * Copy - an eyebrow, a heading and a subtext - is stored once per section
 * rather than repeated on every entry, keyed by the page and section together.
 * The pair is what is unique: the ERP page has a 'faq' and so does the home
 * page, and they are different content.
 *
 * Mirrored by CHECK constraints on page_section_copy, so a key here always
 * exists in the database and a key checked in code always exists here.
 *
 * The home page's hero is deliberately absent: its slides each carry their own
 * eyebrow, heading and subtext, because the carousel shows four different
 * pitches. The ERP page's hero is listed because its slider shares one.
 */
export const PAGE_SECTION_KEYS = {
  home: ['trust', 'industries', 'values', 'integrations', 'testimonials', 'faq', 'cta'],
  erp: [
    'trust',
    'recognition',
    'benefits',
    'alternatives',
    'outcomes',
    'establishers',
    'faq',
    'cta',
  ],
  /*
   * The hero is absent on purpose, here as on the other pages: its slides each
   * carry their own eyebrow, headline and subhead, because the slider shows
   * five different pitches rather than one.
   */
  'sfa-dms': [
    'proof',
    'video',
    'packages',
    'alternatives',
    'outcomes',
    'establishers',
    'faq',
    'cta',
  ],
  /*
   * The hero is absent on purpose, here as on the other pages: its slides each
   * carry their own eyebrow, headline and subhead.
   */
  fms: ['faq', 'cta'],
  /*
   * The first industry page. The hero is absent for the same reason it is
   * everywhere else - each slide carries its own copy.
   */
  bakery: ['trust', 'platform', 'helps', 'faq', 'cta'],
  // The second industry page - the same sections less How UpWON Helps.
  fmcg: ['trust', 'platform', 'faq', 'cta'],
  // The third industry page - the same sections as FMCG Distribution.
  sweets: ['trust', 'platform', 'faq', 'cta'],
  // The fourth and fifth industry pages, which add the coverage grid - and on
  // Non-Food FMCG the capability cards and the benefits grid.
  'food-processing': ['trust', 'platform', 'coverage', 'faq', 'cta'],
  'non-food-fmcg': ['trust', 'capabilities', 'platform', 'benefits', 'coverage', 'faq', 'cta'],
  dairy: ['trust', 'capabilities', 'platform', 'benefits', 'coverage', 'faq', 'cta'],
} as const;

export const PAGE_KEYS = Object.keys(PAGE_SECTION_KEYS) as Array<keyof typeof PAGE_SECTION_KEYS>;

export type PageKey = (typeof PAGE_KEYS)[number];

/** Every section key any page uses, for the one CHECK the table carries. */
export type SectionKey = (typeof PAGE_SECTION_KEYS)[PageKey][number];

export const isSectionOfPage = (pageKey: string, sectionKey: string): boolean =>
  (PAGE_KEYS as readonly string[]).includes(pageKey) &&
  (PAGE_SECTION_KEYS[pageKey as PageKey] as readonly string[]).includes(sectionKey);

